'use client'
import { useState } from 'react';
import CustomNavbar from '@/components/navbar'
// import { NextUIProvider } from "@nextui-org/react";
import './globals.css'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [page, setPage] = useState('');

  return (
    <html lang="en">
      <link rel="icon" type="image/png" sizes="32x32" href="./assets/favicon-32x32.png"></link>
      <title>Frontend Mentor | Space tourism website</title>
      <body>
        <div className={`${page}-bg main`}>
          {/* <NextUIProvider> */}
            <CustomNavbar setPage={setPage} />
            {children}
          {/* </NextUIProvider> */}
        </div>
      </body>
    </html>
  )
}
