'use client'
import { useState } from 'react';
import CustomNavbar from '@/components/navbar'
// import { NextUIProvider } from "@nextui-org/react";
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [page, setPage] = useState('');

  return (
    <html lang="en">
      <body>
        <main className={`${page}-bg main`}>
          {/* <NextUIProvider> */}
            <CustomNavbar setPage={setPage} />
            {children}
          {/* </NextUIProvider> */}
        </main>
      </body>
    </html>
  )
}
